### ISSUE TITLE
Invalid double

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/electrum_adapter#4]
```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: Invalid double
#0      _JsonStringParser.parseDouble (package:electrum_adapter/client/json_newline_transformer.dart:1525:7)
#1      _ChunkedJsonParser.parseNumber (package:electrum_adapter/client/json_newline_transformer.dart:1449:27)
#2      _ChunkedJsonParser.parse (package:electrum_adapter/client/json_newline_transformer.dart:988:22)
#3      _JsonStringDecoderSink.addSlice (package:electrum_adapter/client/json_newline_transformer.dart:1560:13)
#4      _JsonStringDecoderSink.add (package:electrum_adapter/client/json_newline_transformer.dart:1566:5)
#5      _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#6      _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#7      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#8      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#9      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#10     _SinkTransformerStreamSubscription._add (dart:async/stream_transformers.dart:63:11)
#11     _EventSinkWrapper.add (dart:async/stream_transformers.dart:13:11)
#12     _StringAdapterSink.add (dart:convert/string_conversion.dart:228:11)
#13     _StringAdapterSink.addSlice (dart:convert/string_conversion.dart:233:7)
#14     _Utf8ConversionSink.addSlice (dart:convert/string_conversion.dart:307:20)
#15     _Utf8ConversionSink.add (dart:convert/string_conversion.dart:300:5)
#16     _ConverterStreamEventSink.add (dart:convert/chunked_conversion.dart:69:18)
#17     _SinkTransformerStreamSubscription._handleData (dart:async/stream_transformers.dart:111:24)
#18     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#19     CastStreamSubscription._onData (dart:_internal/async_cast.dart:85:11)
#20     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#21     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#22     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#23     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#24     _StreamController._add (dart:async/stream_controller.dart:658:7)
#25     _StreamController.add (dart:async/stream_controller.dart:606:5)
#26     _Socket._onData (dart:io-patch/socket_patch.dart:2447:41)
#27     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#28     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#29     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#30     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#31     _StreamController._add (dart:async/stream_controller.dart:658:7)
#32     _StreamController.add (dart:async/stream_controller.dart:606:5)
#33     _RawSecureSocket._sendReadEvent (dart:io/secure_socket.dart:1116:19)
#34     Timer._createTimer.<anonymous closure> (dart:async-patch/timer_patch.dart:18:15)
#35     _Timer._runTimers (dart:isolate-patch/timer_impl.dart:398:19)
#36     _Timer._handleMessage (dart:isolate-patch/timer_impl.dart:429:5)
#37     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)
```

**Comment by sneurlax** [comment]
Closed and superceded by #7.  Reopen if this issue reappears even after #7 is implemented.
