### ISSUE TITLE
FormatException

### ISSUE THREAD

**Issue by sneurlax** [cypherstack/electrum_adapter#5]
```
#8      _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#9      _SinkTransformerStreamSubscription._close (dart:async/stream_transformers.dart:87:11)
#10     _EventSinkWrapper.close (dart:async/stream_transformers.dart:21:11)
#11     _StringAdapterSink.close (dart:convert/string_conversion.dart:241:11)
#12     _Utf8ConversionSink.close (dart:convert/string_conversion.dart:295:20)
#13     _ConverterStreamEventSink.close (dart:convert/chunked_conversion.dart:78:18)
#14     _SinkTransformerStreamSubscription._handleDone (dart:async/stream_transformers.dart:132:24)
#15     _RootZone.runGuarded (dart:async/zone.dart:1582:10)
#16     _BufferingStreamSubscription._sendDone.sendDone (dart:async/stream_impl.dart:392:13)
#17     _BufferingStreamSubscription._sendDone (dart:async/stream_impl.dart:402:7)
#18     _BufferingStreamSubscription._close (dart:async/stream_impl.dart:291:7)
#19     _SyncStreamControllerDispatch._sendDone (dart:async/stream_controller.dart:792:19)
#20     _StreamController._closeUnchecked (dart:async/stream_controller.dart:647:7)
#21     _StreamController.close (dart:async/stream_controller.dart:640:5)
#22     _Socket._onData (dart:io-patch/socket_patch.dart:2454:21)
#23     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#24     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#25     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#26     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#27     _StreamController._add (dart:async/stream_controller.dart:658:7)
#28     _StreamController.add (dart:async/stream_controller.dart:606:5)
#29     _RawSecureSocket._closeHandler (dart:io/secure_socket.dart:899:21)
#30     _RawSecureSocket._eventDispatcher (dart:io/secure_socket.dart:856:9)
#31     _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
#32     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
#33     _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
#34     _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
#35     _StreamController._add (dart:async/stream_controller.dart:658:7)
#36     _StreamController.add (dart:async/stream_controller.dart:606:5)
#37     new _RawSocket.<anonymous closure> (dart:io-patch/socket_patch.dart:1943:35)
#38     _NativeSocket.issueReadEvent.issue (dart:io-patch/socket_patch.dart:1372:18)
#39     _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
#40     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
```

**Comment by sneurlax** [comment]
Closed and superceded by #7.  Reopen if this issue reappears even after #7 is implemented.
